<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Yg6KnU7' shared service.

return $this->privates['.service_locator.Yg6KnU7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'location' => ['privates', '.errored..service_locator.Yg6KnU7.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.Yg6KnU7": it references class "App\\Entity\\Location" but no such service exists.'],
]);
