<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Tg9qkSo' shared service.

return $this->privates['.service_locator.Tg9qkSo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'event' => ['privates', '.errored..service_locator.Tg9qkSo.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.Tg9qkSo": it references class "App\\Entity\\Event" but no such service exists.'],
]);
