<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDONacfH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDONacfH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDONacfH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDONacfH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDONacfH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DONacfH',
    'container.build_id' => '3b717d9b',
    'container.build_time' => 1555457846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDONacfH');
