<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlDlqQP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlDlqQP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPlDlqQP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPlDlqQP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPlDlqQP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PlDlqQP',
    'container.build_id' => '0772fa1b',
    'container.build_time' => 1561534811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlDlqQP');
